version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./config/recording_rules.yml:/etc/prometheus/recording_rules.yml
      - ./config/dynamic_targets.json:/etc/prometheus/dynamic_targets.json
  promlens:
    image: prom/promlens
    ports:
      - 8080:8080
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
